name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: Get changed files in source folder
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Install dependencies
        run: pnpm install

      - name: Run code quality format check
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: pnpm exec prettier --check --ignore-unknown ${ALL_CHANGED_FILES}

      - name: Run code quality lint check
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: pnpm exec eslint --no-warn-ignored ${ALL_CHANGED_FILES}

      - name: Build
        run: pnpm run build

      - name: Check exports
        run: pnpm run check:exports
